services:
  db:
    image: postgres:18
    restart: always
    shm_size: 1gb
    environment:
      POSTGRES_USER: dropspot
      POSTGRES_PASSWORD: dropspot
      POSTGRES_DB: dropspot
    ports:
      - "5432:5432"
    networks:
      - dropspot
    # volumes:
    #   - db_data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DROPSPOT_DATABASE_URL: "postgres://dropspot:dropspot@db:5432/dropspot"
        DROPSPOT_ENDPOINT: "http://localhost:8000"
        DROPSPOT_PORT: 8000
        SHOULD_MIGRATE: "no-migrate"
    environment:
      DROPSPOT_DATABASE_URL: "postgres://dropspot:dropspot@db:5432/dropspot"
      DROPSPOT_ENDPOINT: "http://localhost:8000"
      DROPSPOT_PORT: 8000
    ports:
      - "8000:8000"
    networks:
      - dropspot
    depends_on:
      - db
    profiles:
      - api


volumes:
  db_data:

networks:
  dropspot:
    driver: bridge
