envVarGroups:
  - name: api-env
    envVars:
      - key: KEY
        value: VALUE
      - key: SQLX_OFFLINE
        value: false # Compile against the live database. It should be migrated before the build starts

projects:
  - name: dropspot-render-template
    environments:
      - name: production
        services:
          - type: web
            name: dropspot-api
            runtime: rust
            plan: starter
            branch: sqlx-offline
            autoDeploy: false
            healthCheckPath: /api/health
            buildCommand: ./scripts/deploy-build.sh
            preDeployCommand: ./scripts/deploy-pre-deploy.sh
            startCommand: ./scripts/deploy-start.sh
            envVars:
              - fromGroup: api-env
              - key: DROPSPOT_DATABASE_URL
                fromDatabase:
                  name: dropspot-db
                  property: connectionString
              - key: DROPSPOT_ENDPOINT
                fromService:
                  type: web
                  name: dropspot-api
                  property: host
              - key: DROPSPOT_PORT
                value: 10000
            disk:
              name: files
              mountPath: /opt/data
              sizeGB: 5
            domains:
              - dropspot.au
              - www.dropspot.au
            renderSubdomainPolicy: disabled

        databases:
          - name: dropspot-db
            databaseName: dropspot
            plan: free
            postgresMajorVersion: 18
            user: dropspot
            region: oregon
            ipAllowList: [] # Only allow internal connections
